#!/usr/bin/env bash
# run nginx as 'nginx' user and listen on port 8080
sed -i "s/#\?user.*/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
service nginx restart
